--Find the total revenue generated by each customer

SELECT c.customerid, c.customername,
SUM(o.quantity * p.price) AS total_revenue
FROM customer__ c JOIN order__ o
ON c.customerid = o.customerid JOIN product__ p
ON o.productid = p.productid
GROUP BY c.customerid, c.customername
ORDER BY total_revenue DESC;

--Find products whose cost price is below the average cost price

SELECT productid,productname,costprice
FROM product__
WHERE costprice < (SELECT AVG(costprice) FROM product__);