--Find the total profit generated by each product

SELECT p.productid,p.productname,
SUM(o.quantity * (p.price - p.costprice)) AS total_profit
FROM product__ p JOIN order__ o
ON p.productid = o.productid
GROUP BY p.productid, p.productname
ORDER BY total_profit DESC;

--Find customers who have purchased products from more than 2 categories

SELECT c.customerid,c.customername,
COUNT(DISTINCT p.category) AS category_count
FROM customer__ c JOIN order__ o
ON c.customerid = o.customerid JOIN product__ p
ON o.productid = p.productid
GROUP BY c.customerid, c.customername
HAVING COUNT(DISTINCT p.category) > 2;


