--Find the total sales amount generated by each product
SELECT 
    p.ProductID,
    p.ProductName,
    SUM(o.Quantity * p.Price) AS TotalSales
FROM product__ p
JOIN order__ o
    ON p.ProductID = o.ProductID
GROUP BY p.ProductID, p.ProductName;

--Find the top 3 products based on total sales
SELECT TOP 3
    p.ProductID,
    p.ProductName,
    SUM(o.Quantity * p.Price) AS TotalSales
FROM product__ p
JOIN order__ o
    ON p.ProductID = o.ProductID
GROUP BY p.ProductID, p.ProductName
ORDER BY TotalSales DESC;