--Find the average order value for each customer.
SELECT 
    c.CustomerID,
    c.CustomerName,
    AVG(o.Quantity * o.UnitPrice) AS AverageOrderValue
FROM customer__ c
JOIN order__ o
    ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.CustomerName
ORDER BY AverageOrderValue DESC;

--Find the total profit generated by each product.
SELECT 
    p.ProductID,
    p.ProductName,
    SUM((o.UnitPrice - p.CostPrice) * o.Quantity) AS TotalProfit
FROM product__ p
JOIN order__ o
    ON p.ProductID = o.ProductID
GROUP BY p.ProductID, p.ProductName
ORDER BY TotalProfit DESC;