--Find the number of customers for each product

SELECT p.productid,p.productname,COUNT(DISTINCT o.customerid) AS customer_count
FROM product__ p
LEFT JOIN order__ o
ON p.productid = o.productid
GROUP BY p.productid, p.productname;

--Find the total revenue generated by each employee

SELECT e.employeeid,e.employeename,SUM(o.quantity * p.price) AS total_revenue
FROM employee__ e
JOIN order__ o
ON e.employeeid = o.employeeid
JOIN product__ p
ON o.productid = p.productid
GROUP BY e.employeeid, e.employeename
ORDER BY total_revenue DESC;