--Find the total number of orders and total revenue generated by each employee.
SELECT 
    e.EmployeeID,
    e.EmployeeName,
    COUNT(o.OrderID) AS TotalOrders,
    SUM(o.Quantity * o.UnitPrice) AS TotalRevenue
FROM employee__ e
LEFT JOIN order__ o
    ON e.EmployeeID = o.EmployeeID
GROUP BY e.EmployeeID, e.EmployeeName
ORDER BY TotalRevenue DESC;

--Find products whose stock quantity is below their reorder level.
SELECT 
    ProductID,
    ProductName,
    StockQuantity,
    ReorderLevel
FROM product__
WHERE StockQuantity < ReorderLevel;

