--Find the customer who has placed the highest number of orders.

SELECT TOP 1 c.CustomerID,c.CustomerName,COUNT(o.OrderID) AS TotalOrders
FROM customer__ c
INNER JOIN order__ o
ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.CustomerName
ORDER BY TotalOrders DESC;

--Find the total profit generated by each category.

SELECT p.Category,SUM(o.Quantity * (p.Price - p.CostPrice)) AS TotalProfit
FROM product__ p
INNER JOIN order__ o
ON p.ProductID = o.ProductID
GROUP BY p.Category
ORDER BY TotalProfit DESC;