--Find orders whose value is greater than ₹5,000

SELECT o.orderid,o.customerid,o.productid,o.quantity * p.price AS order_value
FROM order__ o
JOIN product__ p
ON o.productid = p.productid
WHERE o.quantity * p.price > 5000;

--Find the percentage of total revenue generated by each category

SELECT p.category,SUM(o.quantity * p.price) AS category_revenue,
ROUND(SUM(o.quantity * p.price) * 100.0 /SUM(SUM(o.quantity * p.price)) OVER (),2) AS revenue_percentage
FROM product__ p
JOIN order__ o
ON p.productid = o.productid
GROUP BY p.category;