--Find the revenue generated by each payment method.

SELECT PaymentMethod,COUNT(OrderID) AS TotalOrders,SUM(Quantity * UnitPrice) AS TotalRevenue
FROM order__
GROUP BY PaymentMethod
ORDER BY TotalRevenue DESC;

--Find the running total of revenue for each customer based on order date.

SELECT CustomerID,OrderID,OrderDate,Quantity * UnitPrice AS OrderRevenue,
SUM(Quantity * UnitPrice) OVER (PARTITION BY CustomerID ORDER BY OrderDate, OrderID) AS RunningRevenue
FROM order__
ORDER BY CustomerID, OrderDate, OrderID;